### FRONT ###
/sitemap.xml:
  controller: Base
  action: sitemap
  label: Sitemap
### ### ###

### BACK ADMIN ###
/admin:
  controller: Base
  action: default

/admin/dashboard:
  controller: Base
  action: dashboard
  label: Tableau de bord
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_home

/admin/articles:
  controller: Article
  action: default
  label: Articles
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_page
    children: [
      /admin/add-article,
      /admin/categories
    ]

/admin/add-article:
  controller: Article
  action: addarticle
  label: Ajouter un article

/admin/edit-article:
  controller: Article
  action: editArticle
  label: Modifier un article

/admin/delete-article:
  controller: Article
  action: deleteArticle

/admin/categories:
  controller: Article
  action: categories
  label: Catégories

/admin/edit-category:
  controller: Article
  action: editcategory
  label: Modifier une catégorie

/admin/delete-category:
  controller: Article
  action: deleteCategory

/admin/users:
  controller: Users
  action: default
  label: Utilisateurs
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_user
    children: [
        /admin/add-users,
  ]

/admin/add-users:
  controller: Users
  action: addUsers
  label: Ajouter un utilisateur
  menuData:
    visible: false
    min-statut: true
    listId: basics
    icon: icon_user

/admin/edit-user:
  controller: Users
  action: editUsers
  label: Modifier un utilisateur
  menuData:
    visible: false
    min-statut: true
    listId: basics
    icon: icon_user

/admin/delete-user:
  controller: Users
  action: deleteUser

/admin/pages:
  controller: Page
  action: default
  label: Pages
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Pages
    icon: icon_page
    children: [
        /admin/add-page,
        /admin/deleted-page
    ]

/admin/add-page:
  controller: Page
  action: addpage
  label: Ajouter une page

/admin/edit-page:
  controller: Page
  action: editPage

/admin/delete-page:
  controller: Page
  action: deletePage

/admin/deleted-page:
  controller: Page
  action: listdeletedpage
  label: Corbeille

/admin/comments:
  controller: Comment
  action: default
  label: Commentaires
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_comment


/admin/medias:
  controller: Media
  action: default
  label: Medias
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_media
    children: [
        /admin/add-media
    ]

/admin/roles:
  controller: Role
  action: default
  label: Roles
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_menu
    children: [
      /admin/add-role
    ]

/admin/add-role:
  controller: Role
  action: addrole
  label: Ajouter un role

/admin/edit-role:
  controller: Role
  action: editrole
  label: Modifier un role

/admin/add-media:
  controller: Media
  action: addMedia
  label: Ajouter un média

/admin/edit-medias:
  controller: Media
  action: editMedia
  label: Modifier un média

/admin/delete-media:
  controller: Media
  action: deleteMedia

/admin/template:
  controller: Template
  action: default
  label: Templates
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_page

/admin/template-select:
  controller: Template
  action: change
  label: Templates

/admin/menu-management:
  controller: Menu
  action: default
  label: Gestion du menu
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_menu

/admin/newsletter:
  controller: Newsletter
  action: default
  label: Newsletter
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_newsletter

/:
  controller: WebAccess
  action: default
  label: Accès au site
  menuData:
    visible: true
    min-statut: true
    listId: settings
    icon: icon_web

/admin/settings:
  controller: Settings
  action: default
  label: Paramètres
  menuData:
    visible: true
    min-statut: true
    listId: settings
    icon: icon_settings

/admin/profile:
  controller: Profile
  action: default
  label: Profil
### ### ###

### SECURITY ###
/login:
  controller: Security
  action: login
  label: Connexion
  freeAccess: true

/register:
  controller: Security
  action: register
  label: S'inscrire
  freeAccess: true

/logout:
  controller: Security
  action: logout
  label: Déconnexion
  freeAccess: true

/verification:
  controller: Security
  action: verification
  freeAccess: true

/forgotpassword:
  controller: Security
  action: forgotPassword
  label: Mot de passe oublié
  freeAccess: true

/forgotpasswordconfirm:
  controller: Security
  action: forgotPasswordConfirm
  label: Mot de passe oublié
  freeAccess: true

/newpasswordconfirm:
  controller: Users
  action: newPasswordConfirm
  label: Créer votre nouveau mot de passe
  freeAccess: true
### ### ###

# FRONT ACTION #
/actionfront/postcommentfront:
  controller: Comment
  action: postCommentFromFront
  label: Créer un commentaire
  freeAccess: true
### ### ###

# INSTALLER #
/installer:
  controller: Installer
  action: setup
  label: Installation
  freeAccess: true
  menuData:
    visible: false
    min-statut: true
    listId: installer
    icon: icon_settings
### ### ###