/dashboard:
  controller: Base
  action: dashboard
  label: Tableau de bord
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_home

/articles:
  controller: Article
  action: default
  label: Articles
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_page
    children: [
      /add-article,
      /update-article
    ]

/add-article:
  controller: Article
  action: addarticle
  label: Ajouter un article

/update-article:
  controller: Article
  action: editArticle
  label: Modifier un article

/users:
  controller: User
  action: default
  label: Utilisateurs
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_user

/pages:
  controller: Page
  action: default
  label: Pages
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Pages
    icon: icon_page
    children: [
        /add-page,
        /deleted-page
    ]

/add-page:
  controller: Page
  action: addpage
  label: Ajouter une page

/edit-page:
  controller: Page
  action: editPage

/deleted-page:
  controller: Page
  action: listdeletedpage
  label: Corbeille

/comments:
  controller: Comment
  action: default
  label: Commentaires
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_comment

/medias:
  controller: Media
  action: default
  label: Medias
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_menu
    children: [
      /medias,
      /add-media
    ]

/add-media:
  controller: Media
  action: addMedia
  label: Ajouter média

/template:
  controller: Template
  action: default
  label: Templates
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_page

/menu-management:
  controller: MenuManagement
  action: default
  label: Gestion du menu
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_menu

/newsletter:
  controller: Newsletter
  action: default
  label: Newsletter
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_newsletter

/profile:
  controller: Profile
  action: default
  label: Profil

/login:
  controller: Security
  action: login
  label: Connexion
  freeAccess: true

/register:
  controller: Security
  action: register
  label: S'inscrire
  freeAccess: true

/verification:
  controller: Security
  action: verification
  freeAccess: true

/forgotpassword:
  controller: Security
  action: forgotPassword
  label: Mot de passe oublié
  freeAccess: true

/forgotpasswordconfirm:
  controller: Security
  action: forgotPasswordConfirm
  label: Mot de passe oublié
  freeAccess: true

/logout:
  controller: Security
  action: logout
  label: Déconnexion
  freeAccess: true

/web-access:
  controller: WebAccess
  action: default
  label: Accès au site
  menuData:
    visible: true
    min-statut: true
    listId: settings
    icon: icon_web

/settings:
  controller: Settings
  action: default
  label: Paramètres
  menuData:
    visible: true
    min-statut: true
    listId: settings
    icon: icon_settings

/installer:
  controller: Installer
  action: setup
  label: Installation
  freeAccess: true
  menuData:
    visible: false
    min-statut: true
    listId: installer
    icon: icon_settings