/:
  controller: Base
  action: Default
  label: Accueil
  menuData:
    visible: false
    min-statut: true
    listId: basics
    icon: icon_home

/dashboard:
  controller: Base
  action: dashboard
  label: Tableau de bord
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_home

/articles:
  controller: Article
  action: default
  label: Articles
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_page
    children: [
      /add-article,
      /update-article
    ]

/add-article:
  controller: Article
  action: addarticle
  label: Ajouter un article
  menuData:
    visible: false
    min-statut: true
    listId: basics
    icon: icon_page

/update-article:
  controller: Article
  action: editArticle
  label: Modifier un article
  menuData:
    visible: false
    min-statut: true
    listId: basics
    icon: icon_page

/users:
  controller: Users
  action: default
  label: Utilisateurs
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_user
    children: [
       /add-users,
       /edit-users
  ]

/add-users:
  controller: Users
  action: addUsers
  label: Ajouter un utilisateur
  menuData:
    visible: false
    min-statut: true
    listId: basics
    icon: icon_user

/edit-users:
  controller: Users
  action: editUsers
  label: Modifier un utilisateur
  menuData:
    visible: false
    min-statut: true
    listId: basics
    icon: icon_user

/comments:
  controller: Comment
  action: default
  label: Commentaires
  menuData:
    visible: true
    min-statut: true
    listId: basics
    icon: icon_comment

/template:
  controller: Template
  action: default
  label: Templates
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_page

/menu-management:
  controller: MenuManagement
  action: default
  label: Gestion du menu
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_menu

/newsletter:
  controller: Newsletter
  action: default
  label: Newsletter
  menuData:
    visible: true
    min-statut: true
    listId: management
    icon: icon_newsletter

/exam-form:
  controller: Base
  action: form

/register:
  controller: Security
  action: register
  menuData:
    visible: false
    min-statut: false
    listId: inscription
    label: Inscription
    icon: icon_web

/profile:
  controller: Profile
  action: default
  label: Profil
  menuData:
    visible: false
    min-statut: false
    listId: connexion
    icon: icon_user

/login:
  controller: Security
  action: login
  label: Connexion
  menuData:
    visible: false
    min-statut: false
    listId: connexion
    icon: icon_web

/logout:
  controller: Security
  action: logout
  label: Déconnexion
  menuData:
    visible: false
    min-statut: false
    listId: connexion
    icon: icon_web

/liste-des-utilisateurs:
  controller: Security
  action: listofusers

/web-access:
  controller: WebAccess
  action: default
  label: Accès au site
  menuData:
    visible: true
    min-statut: true
    listId: settings
    icon: icon_web

/settings:
  controller: Settings
  action: default
  label: Paramètres
  menuData:
    visible: true
    min-statut: true
    listId: settings
    icon: icon_settings

/installer:
  controller: Installer
  action: setup
  label: Installation
  menuData:
    visible: false
    min-statut: true
    listId: installer
    icon: icon_settings