/:
  controller: Base
  action: Default

/tableau-de-bord:
  controller: Base
  action: dashboard


/s-inscrire:
  controller: Security
  action: register

/login:
  controller: Security
  action: login

/se-connecter:
  controller: Security
  action: login


/logout:
  controller: Security
  action: logout


/liste-des-utilisateurs:
  controller: Security
  action: listofusers