/:
  controller: Base
  action: Default
  menuData:
    visible: false
    min-statut: true
    listId: basics
    label: Accueil
    icon: icon_home


/dashboard:
  controller: Base
  action: dashboard
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Tableau de bord
    icon: icon_home


/articles:
  controller: Article
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Articles
    icon: icon_page

/ajouter-article:
  controller: Article
  action: addarticle
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Ajouter un article
    icon: icon_page

/modifier-article:
  controller: Article
  action: editArticle
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Modifier un article
    icon: icon_page



/users:
  controller: User
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Utilisateurs
    icon: icon_user

/pages:
  controller: Page
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Pages
    icon: icon_page

/comments:
  controller: Comment
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: basics
    label: Commentaires
    icon: icon_comment

/template:
  controller: Template
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: management
    label: Templates
    icon: icon_page

/menu-management:
  controller: MenuManagement
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: management
    label: Gestion du menu
    icon: icon_menu

/newsletter:
  controller: Newsletter
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: management
    label: Newsletter
    icon: icon_newsletter

/s-inscrire:
  controller: Security
  action: register

/exam-form:
  controller: Base
  action: form
  

/login:
  controller: Security
  action: login
  menuData:
    visible: false
    min-statut: false
    listId: connexion
    label: Connexion
    icon: icon_web

/se-connecter:
  controller: Security
  action: login


/logout:
  controller: Security
  action: logout
  menuData:
    visible: false
    min-statut: false
    listId: connexion
    label: Déconnexion
    icon: icon_web


/liste-des-utilisateurs:
  controller: Security
  action: listofusers

/web-access:
  controller: WebAccess
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: settings
    label: Accès au site
    icon: icon_web

/settings:
  controller: Settings
  action: default
  menuData:
    visible: true
    min-statut: true
    listId: settings
    label: Paramètres
    icon: icon_settings

/installer:
  controller: Installer
  action: setup
  menuData:
    visible: false
    min-statut: true
    listId: installer
    label: Installation
    icon: icon_settings